import type { CreatureDefinition } from "./types";

// Battle kits (#364): species with all four roles (attack / guard / status /
// finisher) below are authored; the rest get a derived kit via
// battle/kits.ts getBattleKit().

export const CREATURES: CreatureDefinition[] = [
  {
    id: "mossling",
    name: "Mossling",
    folkloreType: "woodland",
    maxHp: 28,
    attack: 6,
    defense: 4,
    spriteKey: "creature-mossling",
    spriteColor: 0x5a9a4a,
    early: true,
    moves: [
      { id: "tangle", name: "Tangle", power: 6, type: "woodland", accuracy: 100, role: "attack", cooldown: 0 },
      { id: "bark-hide", name: "Bark Hide", power: 0, type: "woodland", accuracy: 100, role: "guard", cooldown: 2, heal: 0.15 },
      { id: "snare", name: "Snare Vine", power: 3, type: "woodland", accuracy: 95, role: "status", cooldown: 2, inflicts: "rooted" },
      { id: "spore", name: "Spore Burst", power: 11, type: "woodland", accuracy: 85, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "ember-wisp",
    name: "Ember Wisp",
    folkloreType: "hearth",
    maxHp: 22,
    attack: 8,
    defense: 3,
    spriteKey: "creature-ember-wisp",
    spriteColor: 0xe87830,
    early: true,
    moves: [
      { id: "flare", name: "Flare", power: 7, type: "hearth", accuracy: 95, role: "attack", cooldown: 0 },
      { id: "glow", name: "Glow", power: 0, type: "hearth", accuracy: 100, role: "guard", cooldown: 2, heal: 0.15 },
      { id: "kindle", name: "Kindle", power: 4, type: "hearth", accuracy: 90, role: "status", cooldown: 2, inflicts: "burn" },
      { id: "flashfire", name: "Flashfire", power: 12, type: "hearth", accuracy: 80, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "brook-nymph",
    name: "Brook Nymph",
    folkloreType: "water",
    maxHp: 26,
    attack: 5,
    defense: 6,
    spriteKey: "creature-brook-nymph",
    spriteColor: 0x4a8ac8,
    early: true,
    moves: [
      { id: "ripple", name: "Ripple", power: 6, type: "water", accuracy: 100, role: "attack", cooldown: 0 },
      { id: "still-pool", name: "Still Pool", power: 0, type: "water", accuracy: 100, role: "guard", cooldown: 2, heal: 0.2 },
      { id: "splash", name: "Splash", power: 3, type: "water", accuracy: 95, role: "status", cooldown: 2, inflicts: "soaked" },
      { id: "current", name: "Current", power: 11, type: "water", accuracy: 85, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "stone-hound",
    name: "Stone Hound",
    folkloreType: "earth",
    maxHp: 34,
    attack: 7,
    defense: 8,
    spriteKey: "creature-stone-hound",
    spriteColor: 0x7a7a82,
    early: false,
    moves: [
      { id: "bark", name: "Bark", power: 6, type: "earth", accuracy: 100, role: "attack", cooldown: 0 },
      { id: "hunker", name: "Hunker", power: 0, type: "earth", accuracy: 100, role: "guard", cooldown: 2, heal: 0.15 },
      { id: "pin", name: "Pin Down", power: 4, type: "earth", accuracy: 90, role: "status", cooldown: 2, inflicts: "rooted" },
      { id: "ram", name: "Ram", power: 13, type: "earth", accuracy: 75, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "mist-serpent",
    name: "Mist Serpent",
    folkloreType: "mist",
    maxHp: 30,
    attack: 9,
    defense: 4,
    spriteKey: "creature-mist-serpent",
    spriteColor: 0x9a8ac0,
    early: false,
    moves: [
      { id: "haze", name: "Haze", power: 6, type: "mist", accuracy: 95 },
      { id: "coil", name: "Coil", power: 10, type: "mist", accuracy: 80 },
      { id: "drift", name: "Drift", power: 7, type: "mist", accuracy: 90 },
    ],
  },
  {
    id: "rootwalker",
    name: "Rootwalker",
    folkloreType: "woodland",
    maxHp: 32,
    attack: 6,
    defense: 7,
    spriteKey: "creature-rootwalker",
    spriteColor: 0x6a5030,
    early: false,
    moves: [
      { id: "stomp", name: "Stomp", power: 7, type: "woodland", accuracy: 95, role: "attack", cooldown: 0 },
      { id: "bloom", name: "Bloom", power: 0, type: "woodland", accuracy: 100, role: "guard", cooldown: 2, heal: 0.2 },
      { id: "root-grip", name: "Root Grip", power: 4, type: "woodland", accuracy: 90, role: "status", cooldown: 2, inflicts: "rooted" },
      { id: "timberfall", name: "Timberfall", power: 12, type: "woodland", accuracy: 80, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "lantern-fox",
    name: "Lantern Fox",
    folkloreType: "twilight",
    maxHp: 24,
    attack: 8,
    defense: 5,
    spriteKey: "creature-lantern-fox",
    spriteColor: 0xe8c040,
    early: false,
    moves: [
      { id: "gleam", name: "Gleam", power: 7, type: "twilight", accuracy: 95, role: "attack", cooldown: 0 },
      { id: "flicker", name: "Flicker", power: 0, type: "twilight", accuracy: 100, role: "guard", cooldown: 2, heal: 0.1 },
      { id: "dazzle", name: "Dazzle", power: 3, type: "twilight", accuracy: 95, role: "status", cooldown: 2, inflicts: "dazed" },
      { id: "dash", name: "Dash", power: 11, type: "twilight", accuracy: 85, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "thunder-finch",
    name: "Thunder Finch",
    folkloreType: "storm",
    maxHp: 20,
    attack: 10,
    defense: 3,
    spriteKey: "creature-thunder-finch",
    spriteColor: 0xd0d8f0,
    early: false,
    moves: [
      { id: "peck", name: "Peck", power: 6, type: "storm", accuracy: 100 },
      { id: "bolt", name: "Bolt", power: 12, type: "storm", accuracy: 70 },
    ],
  },
  {
    id: "bramblewarden",
    name: "Bramblewarden",
    folkloreType: "woodland",
    maxHp: 42,
    attack: 9,
    defense: 7,
    spriteKey: "creature-bramblewarden",
    spriteColor: 0x3a7a32,
    early: true,
    moves: [
      { id: "bramble", name: "Bramble", power: 9, type: "woodland", accuracy: 95, role: "attack", cooldown: 0 },
      { id: "ward", name: "Ward", power: 0, type: "woodland", accuracy: 100, role: "guard", cooldown: 2, heal: 0.2 },
      { id: "spore", name: "Spore", power: 4, type: "woodland", accuracy: 90, role: "status", cooldown: 2, inflicts: "rooted" },
      { id: "thornquake", name: "Thornquake", power: 14, type: "woodland", accuracy: 80, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "hearthflame",
    name: "Hearthflame",
    folkloreType: "hearth",
    maxHp: 34,
    attack: 12,
    defense: 5,
    spriteKey: "creature-hearthflame",
    spriteColor: 0xff6020,
    early: true,
    moves: [
      { id: "scorch", name: "Scorch", power: 9, type: "hearth", accuracy: 95, role: "attack", cooldown: 0 },
      { id: "warmth", name: "Warmth", power: 0, type: "hearth", accuracy: 100, role: "guard", cooldown: 2, heal: 0.2 },
      { id: "kindle", name: "Kindle", power: 5, type: "hearth", accuracy: 90, role: "status", cooldown: 2, inflicts: "burn" },
      { id: "blaze", name: "Blaze", power: 15, type: "hearth", accuracy: 80, role: "finisher", cooldown: 3 },
    ],
  },
  {
    id: "peat-sprite",
    name: "Peat Sprite",
    folkloreType: "fen",
    maxHp: 28,
    attack: 7,
    defense: 6,
    spriteKey: "creature-peat-sprite",
    spriteColor: 0x8a6038,
    early: false,
    moves: [
      { id: "mire", name: "Mire", power: 7, type: "fen", accuracy: 95 },
      { id: "smolder", name: "Smolder", power: 9, type: "fen", accuracy: 85 },
    ],
  },
  {
    id: "cinder-toad",
    name: "Cinder Toad",
    folkloreType: "ember",
    maxHp: 30,
    attack: 8,
    defense: 6,
    spriteKey: "creature-cinder-toad",
    spriteColor: 0xd06030,
    early: false,
    moves: [
      { id: "hop", name: "Hop", power: 6, type: "ember", accuracy: 100 },
      { id: "ember-spit", name: "Ember Spit", power: 11, type: "ember", accuracy: 75 },
      { id: "ash", name: "Ash", power: 5, type: "ember", accuracy: 95 },
    ],
  },
  {
    id: "bog-lantern",
    name: "Bog Lantern",
    folkloreType: "will-o-wisp",
    maxHp: 22,
    attack: 10,
    defense: 4,
    spriteKey: "creature-bog-lantern",
    spriteColor: 0xffc050,
    early: false,
    moves: [
      { id: "lure", name: "Lure", power: 6, type: "will-o-wisp", accuracy: 95 },
      { id: "flare", name: "Flare", power: 10, type: "will-o-wisp", accuracy: 80 },
      { id: "drift", name: "Drift", power: 7, type: "will-o-wisp", accuracy: 90 },
    ],
  },
  {
    id: "isle-fernling",
    name: "Isle Fernling",
    folkloreType: "woodland",
    maxHp: 27,
    attack: 7,
    defense: 5,
    spriteKey: "creature-isle-fernling",
    spriteColor: 0x3a9a58,
    early: false,
    moves: [
      { id: "frond", name: "Frond", power: 6, type: "woodland", accuracy: 100 },
      { id: "canopy", name: "Canopy", power: 9, type: "woodland", accuracy: 85 },
    ],
  },
  {
    id: "salt-scuttle",
    name: "Salt Scuttle",
    folkloreType: "earth",
    maxHp: 30,
    attack: 8,
    defense: 7,
    spriteKey: "creature-salt-scuttle",
    spriteColor: 0xc8b090,
    early: false,
    moves: [
      { id: "pinch", name: "Pinch", power: 7, type: "earth", accuracy: 95 },
      { id: "scuttle", name: "Scuttle", power: 10, type: "earth", accuracy: 80 },
      { id: "shell", name: "Shell", power: 5, type: "earth", accuracy: 100 },
    ],
  },
  {
    id: "shoal-wisp",
    name: "Shoal Wisp",
    folkloreType: "water",
    maxHp: 24,
    attack: 9,
    defense: 4,
    spriteKey: "creature-shoal-wisp",
    spriteColor: 0x58b8c8,
    early: false,
    moves: [
      { id: "spray", name: "Spray", power: 6, type: "water", accuracy: 100 },
      { id: "undertow", name: "Undertow", power: 11, type: "water", accuracy: 75 },
      { id: "drift", name: "Drift", power: 7, type: "water", accuracy: 90 },
    ],
  },
  // Archipelago islands 3–15 (index % 3 cycles lush/barren/other flavor).
  {
    id: "tide-urchin",
    name: "Tide Urchin",
    folkloreType: "water",
    maxHp: 28,
    attack: 8,
    defense: 8,
    spriteKey: "creature-tide-urchin",
    spriteColor: 0x3a6a98,
    early: false,
    moves: [
      { id: "bristle", name: "Bristle", power: 7, type: "water", accuracy: 95 },
      { id: "surge", name: "Surge", power: 11, type: "water", accuracy: 75 },
    ],
  },
  {
    id: "coral-skitter",
    name: "Coral Skitter",
    folkloreType: "earth",
    maxHp: 26,
    attack: 9,
    defense: 6,
    spriteKey: "creature-coral-skitter",
    spriteColor: 0xe07868,
    early: false,
    moves: [
      { id: "scrape", name: "Scrape", power: 7, type: "earth", accuracy: 95 },
      { id: "skitter", name: "Skitter", power: 10, type: "earth", accuracy: 80 },
    ],
  },
  {
    id: "drift-kelpie",
    name: "Drift Kelpie",
    folkloreType: "water",
    maxHp: 30,
    attack: 8,
    defense: 5,
    spriteKey: "creature-drift-kelpie",
    spriteColor: 0x2a8a70,
    early: false,
    moves: [
      { id: "tangle-kelp", name: "Tangle Kelp", power: 6, type: "water", accuracy: 100 },
      { id: "pull", name: "Pull", power: 11, type: "water", accuracy: 75 },
    ],
  },
  {
    id: "dune-hermit",
    name: "Dune Hermit",
    folkloreType: "woodland",
    maxHp: 29,
    attack: 7,
    defense: 8,
    spriteKey: "creature-dune-hermit",
    spriteColor: 0xc8a060,
    early: false,
    moves: [
      { id: "burrow", name: "Burrow", power: 6, type: "woodland", accuracy: 100 },
      { id: "shell-rattle", name: "Shell Rattle", power: 10, type: "woodland", accuracy: 80 },
    ],
  },
  {
    id: "brackish-newt",
    name: "Brackish Newt",
    folkloreType: "fen",
    maxHp: 27,
    attack: 8,
    defense: 5,
    spriteKey: "creature-brackish-newt",
    spriteColor: 0x5a8860,
    early: false,
    moves: [
      { id: "slip", name: "Slip", power: 6, type: "fen", accuracy: 100 },
      { id: "brine", name: "Brine", power: 10, type: "fen", accuracy: 80 },
    ],
  },
  {
    id: "pearl-moth",
    name: "Pearl Moth",
    folkloreType: "mist",
    maxHp: 22,
    attack: 9,
    defense: 3,
    spriteKey: "creature-pearl-moth",
    spriteColor: 0xe8d8f0,
    early: false,
    moves: [
      { id: "flutter", name: "Flutter", power: 5, type: "mist", accuracy: 100 },
      { id: "pearl-dust", name: "Pearl Dust", power: 10, type: "mist", accuracy: 80 },
    ],
  },
  {
    id: "reef-spinner",
    name: "Reef Spinner",
    folkloreType: "water",
    maxHp: 25,
    attack: 10,
    defense: 4,
    spriteKey: "creature-reef-spinner",
    spriteColor: 0x48a8b8,
    early: false,
    moves: [
      { id: "spin", name: "Spin", power: 7, type: "water", accuracy: 95 },
      { id: "reel", name: "Reel", power: 11, type: "water", accuracy: 75 },
    ],
  },
  {
    id: "mist-anemone",
    name: "Mist Anemone",
    folkloreType: "mist",
    maxHp: 28,
    attack: 6,
    defense: 7,
    spriteKey: "creature-mist-anemone",
    spriteColor: 0xa8b8d0,
    early: false,
    moves: [
      { id: "tendril", name: "Tendril", power: 6, type: "mist", accuracy: 100 },
      { id: "veil", name: "Veil", power: 9, type: "mist", accuracy: 85 },
    ],
  },
  {
    id: "barnacle-toad",
    name: "Barnacle Toad",
    folkloreType: "earth",
    maxHp: 32,
    attack: 7,
    defense: 8,
    spriteKey: "creature-barnacle-toad",
    spriteColor: 0x708060,
    early: false,
    moves: [
      { id: "plod", name: "Plod", power: 6, type: "earth", accuracy: 100 },
      { id: "clamp", name: "Clamp", power: 10, type: "earth", accuracy: 80 },
    ],
  },
  {
    id: "gulf-lantern",
    name: "Gulf Lantern",
    folkloreType: "will-o-wisp",
    maxHp: 23,
    attack: 10,
    defense: 3,
    spriteKey: "creature-gulf-lantern",
    spriteColor: 0xffb060,
    early: false,
    moves: [
      { id: "beckon", name: "Beckon", power: 6, type: "will-o-wisp", accuracy: 95 },
      { id: "gulf-flare", name: "Gulf Flare", power: 11, type: "will-o-wisp", accuracy: 75 },
    ],
  },
  {
    id: "spray-finch",
    name: "Spray Finch",
    folkloreType: "storm",
    maxHp: 24,
    attack: 10,
    defense: 4,
    spriteKey: "creature-spray-finch",
    spriteColor: 0x70a8d0,
    early: false,
    moves: [
      { id: "chirp", name: "Chirp", power: 5, type: "storm", accuracy: 100 },
      { id: "spray-gust", name: "Spray Gust", power: 11, type: "storm", accuracy: 75 },
    ],
  },
  {
    id: "lagoon-hare",
    name: "Lagoon Hare",
    folkloreType: "woodland",
    maxHp: 26,
    attack: 8,
    defense: 5,
    spriteKey: "creature-lagoon-hare",
    spriteColor: 0x88c090,
    early: false,
    moves: [
      { id: "bound", name: "Bound", power: 7, type: "woodland", accuracy: 95 },
      { id: "lagoon-kick", name: "Lagoon Kick", power: 10, type: "woodland", accuracy: 80 },
    ],
  },
  {
    id: "atoll-wisp",
    name: "Atoll Wisp",
    folkloreType: "water",
    maxHp: 22,
    attack: 9,
    defense: 3,
    spriteKey: "creature-atoll-wisp",
    spriteColor: 0x68d0c8,
    early: false,
    moves: [
      { id: "shimmer", name: "Shimmer", power: 6, type: "water", accuracy: 100 },
      { id: "ring-tide", name: "Ring Tide", power: 10, type: "water", accuracy: 80 },
    ],
  },
  {
    id: "tide-sovereign",
    name: "Tide Sovereign",
    folkloreType: "water",
    maxHp: 96,
    attack: 16,
    defense: 14,
    spriteKey: "creature-tide-sovereign",
    spriteColor: 0x075f68,
    early: false,
    excludeFromCodex: true,
    moves: [
      { id: "still-tide", name: "Still Tide", power: 10, type: "water", accuracy: 100 },
      { id: "abyss-surge", name: "Abyss Surge", power: 15, type: "water", accuracy: 100 },
      { id: "crown-crash", name: "Crown Crash", power: 20, type: "water", accuracy: 100 },
    ],
  },
  {
    id: "cairn-sovereign",
    name: "Stone Sovereign",
    folkloreType: "earth",
    maxHp: 108,
    attack: 14,
    defense: 18,
    spriteKey: "creature-cairn-sovereign",
    spriteColor: 0x6a6458,
    early: false,
    excludeFromCodex: true,
    moves: [
      { id: "grave-hum", name: "Grave Hum", power: 10, type: "earth", accuracy: 100 },
      { id: "cairn-crash", name: "Cairn Crash", power: 15, type: "earth", accuracy: 100 },
      { id: "ridge-fall", name: "Ridge Fall", power: 20, type: "earth", accuracy: 100 },
    ],
  },
  {
    id: "horizon-sovereign",
    name: "Horizon Sovereign",
    folkloreType: "mist",
    maxHp: 120,
    attack: 20,
    defense: 18,
    spriteKey: "creature-horizon-sovereign",
    spriteColor: 0x7a6a98,
    early: false,
    excludeFromCodex: true,
    moves: [
      { id: "horizon-pulse", name: "Horizon Pulse", power: 12, type: "mist", accuracy: 100 },
      { id: "sovereign-crash", name: "Sovereign Crash", power: 18, type: "earth", accuracy: 90 },
      { id: "abyssal-ridge", name: "Abyssal Ridge", power: 18, type: "water", accuracy: 90 },
      { id: "still-crown", name: "Still Crown", power: 10, type: "mist", accuracy: 100 },
    ],
  },
  {
    id: "eclipse-sovereign",
    name: "Eclipse Sovereign",
    folkloreType: "mist",
    maxHp: 144,
    attack: 24,
    defense: 22,
    spriteKey: "creature-eclipse-sovereign",
    spriteColor: 0x2a2438,
    early: false,
    excludeFromCodex: true,
    moves: [
      { id: "eclipse-pulse", name: "Eclipse Pulse", power: 14, type: "mist", accuracy: 100 },
      { id: "umbral-crash", name: "Umbral Crash", power: 22, type: "earth", accuracy: 90 },
      { id: "abyssal-eclipse", name: "Abyssal Eclipse", power: 22, type: "water", accuracy: 90 },
      { id: "still-eclipse", name: "Still Eclipse", power: 12, type: "mist", accuracy: 100 },
    ],
  },
];

const byId = new Map(CREATURES.map((c) => [c.id, c]));

export function getCreatureDefinition(id: string): CreatureDefinition {
  const creature = byId.get(id);
  if (!creature) {
    throw new Error(`Unknown creature: ${id}`);
  }
  return creature;
}
